version: '3.9'

services:
  redis:
    image: redis:7-alpine
    container_name: redis_apartment_queue
    ports:
      - "6381:6379"  # Host:Container, for local Redis access
    volumes:
      - redis-data:/data
    restart: always
    command: ["redis-server", "--appendonly", "yes"]  # Enable persistence
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  queue-server:
    build: .
    container_name: redis_queue_server
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "3003:3003"
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVER_PORT=3003
    command: npm run dev
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 1.5G

volumes:
  redis-data:
